#!../../bin/linux-x86_64/ndsex1
#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-epics-iter-templates/tags/CODAC-CORE-5.4.0/templates/genericBoot/ioc/st.cmd $
# $Id: st.cmd 75208 2017-02-03 09:19:23Z cesnikt $
#
# Project       : CODAC Core System
#
# Description   : ITER ioc template EPICS start up file
#
# Author(s)     : This file was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2017 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================


< envPaths
< envSystem
< envUser

cd "${TOP}"
## Register all support components
dbLoadDatabase "dbd/ndsex1.dbd"
ndsex1_registerRecordDeviceDriver pdbbase

ndsLoadDriver("$(EXAMPLE_LIB_PATH)/libnds3-exampleDrv.so")
ndsCreateDevice(exampleDrv, "B-0")

## Load record instances
dbLoadTemplate("db/exampleDrv.substitutions")


cd "iocBoot/${IOC}"
iocInit
dbl

## Start any sequence programs
